import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../assets/redux/provider";
import Image from "next/image";
import Logo from "../assets/images/Logo.png";
import "./globals.css";

// Font
const inter = Inter({ subsets: ["latin"] });

// Style image
const logoImageStyle = {
  marginTop: "25px",
  marginBottom: "5px",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col items-center">
            <Image
              src={Logo}
              alt="logo"
              style={logoImageStyle}
              width={180}
              height={180}
            />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
